### ISSUE TITLE
Deep linking support

### ISSUE THREAD

**Issue by salhotra** [react-navigation/redux-helpers#82]
**Use case:**
Need to support deep linking from react navigation.
https://reactnavigation.org/docs/en/deep-linking.html

In order to do that, we need to pass a prop called `uriPrefix` to the top level navigator.

**Problem:**
Right now we can't pass `uriPrefix` (https://reactnavigation.org/docs/en/deep-linking.html#uri-prefix-1) to the Component wrapped by `createReduxContainer`.

Is there a decent way to fire the event listeners in the library for deep linking?

Ps: This library has been very useful for me. Thank you.

**Comment by Ashoat** [comment]
Yeah, you're unfortunately correct that there isn't currently any support for that in this library.

You can see how `createAppContainer` does it [here](https://github.com/react-navigation/react-navigation-native/blob/master/src/createAppContainer.js#L137-L150). Basically, the URI and the `uriPrefix` get passed into [`getParamsFromPath`](https://github.com/react-navigation/react-navigation-core/blob/master/src/routers/pathUtils.js#L9-L37), and the result of that is then passed to the root navigator's router's `getActionForPathAndParams`. That function then returns an action, which is then dispatched.

You should be able to implement this directly. The main navigator's router can be accessed on the Redux container, and `getParamsFromPath` can be imported. You should also take a look at [how `createAppContainer` handles](https://github.com/react-navigation/react-navigation-native/blob/master/src/createAppContainer.js#L241-L259) `Linking.getInitialURL()` on `componentDidMount` (basically replaces the `INIT` action with the `getActionForPathAndParams` action).

**Comment by campfighter** [comment]
Hey, same issue here. Thanks for your help and suggestions. Can you help me understand how to access the main router on the Redux container?

**Comment by Ashoat** [comment]
It’s a static property on the container component. You can give the source code for the container a quick read if you’d like to learn more. Closing this issue now since no response from OP.

**Comment by 5468sun** [comment]
is deep linking supported yet? 
I have the same problem, and dont know how to implement the previous solution.

**Comment by samtoya** [comment]
@Ashoat Is deep linking now supported? If not, can you please give an example on the solution you suggested/recommended?

Thank you.

**Comment by BenjErgizerBunny** [comment]
Is deep linking supported yet with redux?  I also don't understand how to implement the solution above

**Comment by Ashoat** [comment]
Deep linking isn’t supported but PRs would be welcome!

**Comment by scaralfred** [comment]
Any update on this?
