### ISSUE TITLE
How to addListener with react-navigation-redux-helpers?

### ISSUE THREAD

**Issue by hoangpham95** [react-navigation/redux-helpers#84]
Looking at this [tutorial](https://reactnavigation.org/docs/en/custom-android-back-button-handling.html), how can I add listener like this?
```
this.props.navigation.addListener('willBlur', payload =>
      BackHandler.removeEventListener('hardwareBackPress', this.onBackButtonPressAndroid)
);
```

**Comment by Ashoat** [comment]
Not sure what you’re asking. That code snippet will remove the `BackHandler` event listener on blur. Not sure if that’s what you want. For an example of how to implement back handler behavior please check the end of this project’s `README`.
