### ISSUE TITLE
Is there an equivalent onNavigationStateChange prop in the reduxContainer to the appContainer?

### ISSUE THREAD

**Issue by rsouthgate** [react-navigation/redux-helpers#85]
I was reading the React Navigation docs and noticed a useful screen tracking example here:
https://reactnavigation.org/docs/en/screen-tracking.html which uses the top level app container to track screens.

Since I've implemented redux helpers my container is a redux container so I don't think I can or should be doing it the same way. I'm assuming middleware is the right approach with redux but was checking to see what the standard approach is... assuming this has been handled before since tracking seems such a common requirement!

**Comment by Ashoat** [comment]
This is mostly a question about Redux idioms. You have three ways you could do it - a middleware, in the reducers, and in a `connect`ed component.

I think the `connect`ed component is probably the most idiomatic solution. You set up a component that subscribes to your navigation state, and then using the same `getActiveRouteName` from the link you provided, you check if the active route has changed, and if it has you can run your logging/tracking code.

The middleware approach probably isn't bad. The reducer approach would probably be considered a code smell.
