### ISSUE TITLE
Cannot read property 'routes' of undefined

### ISSUE THREAD

**Issue by tusharkhatiwada** [react-navigation/redux-helpers#89]
Hi,
I've been trying to create a new RN project with latest react-navigation, redux-helpers and getting these errors:

**Android**
`Cannot read property 'routes' of undefined`

**iOS**
`undefined is not an object (evaluating 'state.routes')`

Expo Link: https://snack.expo.io/@tushark/react-navigation-v3-redux

Looked into the existing issue: https://github.com/react-navigation/redux-helpers/issues/68
but still failing.
What am I missing here? 

Thanks

**Comment by Ashoat** [comment]
You made a typo. Change line 64 to this and it works:

  const { state: nav, dispatch } = this.props;

**Comment by tusharkhatiwada** [comment]
Thanks a lot. That was definitely the problem.
