### ISSUE TITLE
Changing imports from @react-navigation/core to react-navigation breaks web apps

### ISSUE THREAD

**Issue by jpaas** [react-navigation/redux-helpers#99]
When the imports in the reducer changed from `@react-navigation/core` to `react-navigation` this broke any app using `react-navigation-web` because `react-navigation` imports native modules.

**Comment by Ashoat** [comment]
Oopsie. I'll change it back.

**Comment by Ashoat** [comment]
Okay, I've realized `react-navigation-redux-helpers@3.0.8` (for `react-navigation@3.11` and earlier) and `react-navigation-redux-helpers@4.0.1` (for `react-navigation@3.12` and later).

**Comment by jpaas** [comment]
Thanks @Ashoat! It works again.
